<?php

namespace Database\Seeders;

use App\Models\Book;
use Illuminate\Database\Seeder;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        $books = [
            [
                'title' => 'Web Service Publication Manual for Personal Development',
                'title_transcription' => 'webu sabisu hakkou manyuaru',
                'author' => 'Akira Sakuma',
                'publisher' => 'Shuwa System',
                'published_date' => '2024-01-15',
                'isbn' => '9784798059310',
                'pages' => 320,
                'price' => 3000.00,
                'ndc' => '007.6',
                'quantity' => 3,
                'acceptance_date' => '2024-01-20',
            ],
            [
                'title' => 'Git Basics Explained Easy: 33 Essential Usage Patterns',
                'title_transcription' => 'git kiso shinbun',
                'author' => 'Masashi Ogushi',
                'publisher' => 'Impress',
                'published_date' => '2023-10-01',
                'isbn' => '9784844368687',
                'pages' => 240,
                'price' => 2500.00,
                'ndc' => '007.63',
                'quantity' => 2,
                'acceptance_date' => '2023-10-15',
            ],
            [
                'title' => 'Python Programming for Beginners',
                'title_transcription' => 'python puroguraming',
                'author' => 'Hiroshi Tanaka',
                'publisher' => 'Technical Books',
                'published_date' => '2024-02-10',
                'isbn' => '9784873119938',
                'pages' => 400,
                'price' => 3500.00,
                'ndc' => '007.64',
                'quantity' => 5,
                'acceptance_date' => '2024-02-20',
            ],
            [
                'title' => 'JavaScript Mastery Guide',
                'title_transcription' => 'javascript masutari gaido',
                'author' => 'Kenji Yamamoto',
                'publisher' => 'Web Development Press',
                'published_date' => '2023-08-05',
                'isbn' => '9784798056104',
                'pages' => 480,
                'price' => 4000.00,
                'ndc' => '007.65',
                'quantity' => 4,
                'acceptance_date' => '2023-08-25',
            ],
            [
                'title' => 'Database Design Principles',
                'title_transcription' => 'deetabeesu sekkei',
                'author' => 'Yuki Suzuki',
                'publisher' => 'Database Publishing',
                'published_date' => '2023-09-12',
                'isbn' => '9784873118857',
                'pages' => 350,
                'price' => 3200.00,
                'ndc' => '007.66',
                'quantity' => 3,
                'acceptance_date' => '2023-09-28',
            ],
            [
                'title' => 'Demon Slayer Vol. 1',
                'title_transcription' => 'demon sureiyaa',
                'author' => 'Koyoharu Gotouge',
                'publisher' => 'Jump Comics',
                'published_date' => '2016-05-10',
                'isbn' => '9784088806990',
                'pages' => 192,
                'price' => 440.00,
                'ndc' => '726.1',
                'quantity' => 6,
                'acceptance_date' => '2024-01-10',
            ],
            [
                'title' => 'One Punch Man Vol. 1',
                'title_transcription' => 'wan panchi man',
                'author' => 'ONE',
                'publisher' => 'Jump Comics',
                'published_date' => '2012-10-04',
                'isbn' => '9784088803234',
                'pages' => 192,
                'price' => 440.00,
                'ndc' => '726.1',
                'quantity' => 4,
                'acceptance_date' => '2024-01-15',
            ],
            [
                'title' => 'Attack on Titan Vol. 1',
                'title_transcription' => 'shingeki no kyojin',
                'author' => 'Hajime Isayama',
                'publisher' => 'Weekly Shonen Magazine',
                'published_date' => '2009-10-09',
                'isbn' => '9784063726190',
                'pages' => 192,
                'price' => 440.00,
                'ndc' => '726.1',
                'quantity' => 3,
                'acceptance_date' => '2024-01-12',
            ],
            [
                'title' => 'Mathematics Fundamentals for High School',
                'title_transcription' => 'sugaku kiso',
                'author' => 'Takeshi Nakamura',
                'publisher' => 'Educational Press',
                'published_date' => '2023-04-01',
                'isbn' => '9784491053226',
                'pages' => 450,
                'price' => 2800.00,
                'ndc' => '410',
                'quantity' => 7,
                'acceptance_date' => '2023-04-15',
            ],
            [
                'title' => 'Physics Concepts and Applications',
                'title_transcription' => 'butsuri gainen',
                'author' => 'Hiromi Ito',
                'publisher' => 'Science Press',
                'published_date' => '2023-05-01',
                'isbn' => '9784491051628',
                'pages' => 520,
                'price' => 3100.00,
                'ndc' => '420',
                'quantity' => 5,
                'acceptance_date' => '2023-05-20',
            ],
            [
                'title' => 'English Grammar Complete Reference',
                'title_transcription' => 'eigo bunpou',
                'author' => 'Yoko Yamada',
                'publisher' => 'Language Learning Press',
                'published_date' => '2023-06-10',
                'isbn' => '9784491051321',
                'pages' => 380,
                'price' => 2600.00,
                'ndc' => '830.9',
                'quantity' => 6,
                'acceptance_date' => '2023-06-25',
            ],
            [
                'title' => 'Modern Japanese Literature Collection',
                'title_transcription' => 'gendai nihongo bungaku',
                'author' => 'Yasunari Kawabata',
                'publisher' => 'Classic Literature Press',
                'published_date' => '1999-01-15',
                'isbn' => '9784101060025',
                'pages' => 340,
                'price' => 1800.00,
                'ndc' => '910.26',
                'quantity' => 2,
                'acceptance_date' => '2024-01-05',
            ],
            [
                'title' => 'History of Japan: Edo Period',
                'title_transcription' => 'nihon rekishi edo jidai',
                'author' => 'Etsuko Mori',
                'publisher' => 'History Press',
                'published_date' => '2022-03-20',
                'isbn' => '9784491041895',
                'pages' => 400,
                'price' => 2900.00,
                'ndc' => '210.5',
                'quantity' => 3,
                'acceptance_date' => '2022-04-10',
            ],
            [
                'title' => 'Chemistry Principles and Reactions',
                'title_transcription' => 'kagaku genri',
                'author' => 'Shoji Nakajima',
                'publisher' => 'Chemistry Publishing',
                'published_date' => '2023-07-05',
                'isbn' => '9784491051970',
                'pages' => 480,
                'price' => 3300.00,
                'ndc' => '430',
                'quantity' => 4,
                'acceptance_date' => '2023-07-22',
            ],
            [
                'title' => 'Biology and Life Science',
                'title_transcription' => 'seibutsu kagaku',
                'author' => 'Reiko Hasegawa',
                'publisher' => 'Natural Science Press',
                'published_date' => '2023-08-15',
                'isbn' => '9784491052396',
                'pages' => 420,
                'price' => 3000.00,
                'ndc' => '460',
                'quantity' => 4,
                'acceptance_date' => '2023-09-01',
            ],
            [
                'title' => 'Social Studies: Government and Society',
                'title_transcription' => 'shakaigaku seiji',
                'author' => 'Masaru Yamamoto',
                'publisher' => 'Social Science Press',
                'published_date' => '2023-09-20',
                'isbn' => '9784491052779',
                'pages' => 360,
                'price' => 2700.00,
                'ndc' => '300',
                'quantity' => 5,
                'acceptance_date' => '2023-10-05',
            ],
            [
                'title' => 'World Cultures and Geography',
                'title_transcription' => 'sekai chiri',
                'author' => 'Tomoe Sato',
                'publisher' => 'Geography Press',
                'published_date' => '2023-10-10',
                'isbn' => '9784491052908',
                'pages' => 400,
                'price' => 2800.00,
                'ndc' => '290',
                'quantity' => 3,
                'acceptance_date' => '2023-10-28',
            ],
            [
                'title' => 'Art and Design Fundamentals',
                'title_transcription' => 'geijutsu dezain',
                'author' => 'Hiroshi Nakamura',
                'publisher' => 'Art Press',
                'published_date' => '2023-11-15',
                'isbn' => '9784491053264',
                'pages' => 280,
                'price' => 2400.00,
                'ndc' => '700',
                'quantity' => 2,
                'acceptance_date' => '2023-12-01',
            ],
            [
                'title' => 'Music Theory and Practice',
                'title_transcription' => 'ongaku riron',
                'author' => 'Fumiko Tanaka',
                'publisher' => 'Music Press',
                'published_date' => '2023-12-01',
                'isbn' => '9784491053479',
                'pages' => 320,
                'price' => 2500.00,
                'ndc' => '760',
                'quantity' => 2,
                'acceptance_date' => '2024-01-18',
            ],
        ];

        foreach ($books as $book) {
            Book::create($book);
        }
    }
}
