<?php

namespace Database\Seeders;

use App\Models\Book;
use Illuminate\Database\Seeder;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        $books = [
            [
                'id' => 1,
                'title' => '個人開発のためのWebサービス公開マニュアル : 開発したあと何をしたらいいのか分からない人へ',
                'author' => null,
                'publisher' => '秀和システム',
                'isbn' => '9784798059310',
                'classification' => null,
                'registration_date' => null,
            ],
            [
                'id' => 2,
                'title' => 'Gitが、おもしろいほどわかる基本の使い方33',
                'author' => null,
                'publisher' => null,
                'isbn' => '9784844368687',
                'classification' => null,
                'registration_date' => null,
            ],
            [
                'id' => 3,
                'title' => '汝、星のごとく',
                'author' => '凪良, ゆう',
                'publisher' => '講談社',
                'isbn' => '9784487166688',
                'classification' => null,
                'registration_date' => null,
            ],
            [
                'id' => 4,
                'title' => '大学入試英語リスニング対策差がつく編 : CD付',
                'author' => '旺文社',
                'publisher' => null,
                'isbn' => '9784410804014',
                'classification' => null,
                'registration_date' => null,
            ],
            [
                'id' => 5,
                'title' => '新編数学II',
                'author' => '阿原一志',
                'publisher' => null,
                'isbn' => '9784410804014',
                'classification' => null,
                'registration_date' => null,
            ],
            [
                'id' => 6,
                'title' => '新編数学B',
                'author' => '阿原一志',
                'publisher' => null,
                'isbn' => '9784410804069',
                'classification' => null,
                'registration_date' => null,
            ],
            [
                'id' => 7,
                'title' => '物理のエッセンス熱・電磁気・原子',
                'author' => '浜島清利',
                'publisher' => '河合出版',
                'isbn' => '9784777227242',
                'classification' => null,
                'registration_date' => null,
            ],
            [
                'id' => 8,
                'title' => '新編数学B',
                'author' => '吾峠, 呼世晴,吾峠呼世晴',
                'publisher' => '数研出版',
                'isbn' => '9784410804069',
                'classification' => null,
                'registration_date' => null,
            ],
            [
                'id' => 15,
                'title' => '鬼滅の刃',
                'author' => '吾峠, 呼世晴,吾峠呼世晴',
                'publisher' => '集英社',
                'isbn' => '9784088807232',
                'classification' => null,
                'registration_date' => null,
            ],
            [
                'id' => 16,
                'title' => '大学入試全レベル問題集古文',
                'author' => '伊藤紫野富',
                'publisher' => '旺文社',
                'isbn' => '9784010353578',
                'classification' => null,
                'registration_date' => null,
            ],
            [
                'id' => 17,
                'title' => '竹取物語',
                'author' => '阪倉, 篤義,阪倉篤義 校訂',
                'publisher' => '岩波書店',
                'isbn' => '9784003000717',
                'classification' => null,
                'registration_date' => null,
            ],
            [
                'id' => 18,
                'title' => 'おいしい料理をつくってみよう',
                'author' => '検見崎, 聡美, 1965-,検見崎聡美',
                'publisher' => 'あかね書房',
                'isbn' => '9784251093615',
                'classification' => null,
                'registration_date' => null,
            ],
            [
                'id' => 19,
                'title' => 'ワンパンマン',
                'author' => 'ONE,村田, 雄介,ONE 原作,村田雄介 漫画',
                'publisher' => '集英社',
                'isbn' => '978-4-08-884479-4',
                'classification' => null,
                'registration_date' => null,
            ],
            [
                'id' => 20,
                'title' => 'ドラえもん',
                'author' => '藤子, F. 不二雄,藤子不二雄',
                'publisher' => '小学館',
                'isbn' => '4091400019',
                'classification' => null,
                'registration_date' => null,
            ],
            [
                'id' => 21,
                'title' => '哲学な日々 : 考えさせない時代に抗して',
                'author' => '野矢, 茂樹, 1954-,野矢茂樹',
                'publisher' => '講談社',
                'isbn' => '4062198177',
                'classification' => null,
                'registration_date' => null,
            ],
            [
                'id' => 22,
                'title' => '日本社会事業大学',
                'author' => null,
                'publisher' => '教学社',
                'isbn' => '9784325270812',
                'classification' => null,
                'registration_date' => null,
            ],
            [
                'id' => 23,
                'title' => '神戸女学院大学',
                'author' => 's',
                'publisher' => '教学社',
                'isbn' => '9784325272151',
                'classification' => null,
                'registration_date' => null,
            ],
            [
                'id' => 24,
                'title' => '大阪学院大学',
                'author' => '吾峠, 呼世晴,吾峠呼世晴',
                'publisher' => '教学社',
                'isbn' => '9784325271673',
                'classification' => null,
                'registration_date' => null,
            ],
            [
                'id' => 25,
                'title' => 'a',
                'author' => '田中太郎',
                'publisher' => 'a',
                'isbn' => '9385250000040',
                'classification' => null,
                'registration_date' => null,
            ],
            [
                'id' => 26,
                'title' => 'りんご',
                'author' => 'りんご',
                'publisher' => 'りんご',
                'isbn' => '9385250000057',
                'classification' => null,
                'registration_date' => null,
            ],
            [
                'id' => 27,
                'title' => '祗園祭のカネ',
                'author' => 'a',
                'publisher' => 'a',
                'isbn' => '9385250000064',
                'classification' => null,
                'registration_date' => null,
            ],
            [
                'id' => 28,
                'title' => 'k',
                'author' => 'j',
                'publisher' => 'k',
                'isbn' => '9385250000071',
                'classification' => null,
                'registration_date' => null,
            ],
            [
                'id' => 29,
                'title' => '蔭山のセンター政治・経済',
                'author' => '蔭山, 克秀,蔭山克秀',
                'publisher' => '学研教育出版',
                'isbn' => '9784053033147',
                'classification' => null,
                'registration_date' => null,
            ],
            [
                'id' => 30,
                'title' => '政治・経済問題集',
                'author' => '金子幹夫, 鈴木茂樹, 橋本雅文, 藤井剛',
                'publisher' => '山川出版社',
                'isbn' => '9784634051010',
                'classification' => null,
                'registration_date' => null,
            ],
            [
                'id' => 32,
                'title' => '大学入試英語リスニング対策 : 大学入試即解セミナー',
                'author' => '旺文社,旺文社',
                'publisher' => '旺文社',
                'isbn' => '9784010325964',
                'classification' => null,
                'registration_date' => null,
            ],
            [
                'id' => 33,
                'title' => 'ハーメルンの笛吹き男 : 伝説とその世界',
                'author' => '阿部, 謹也, 1935-2006,阿部謹也',
                'publisher' => '筑摩書房',
                'isbn' => '9784480022721',
                'classification' => null,
                'registration_date' => null,
            ],
            [
                'id' => 34,
                'title' => '銀魂',
                'author' => '空知, 英秋,空知英秋',
                'publisher' => '集英社',
                'isbn' => '4088736230',
                'classification' => null,
                'registration_date' => null,
            ],
            [
                'id' => 36,
                'title' => 'フランダースの犬',
                'author' => 'Ouida, 1839-1908,ルイズ・ド・ラ・ラメー 原作',
                'publisher' => '徳間書店',
                'isbn' => '4198640009',
                'classification' => null,
                'registration_date' => null,
            ],
            [
                'id' => 37,
                'title' => 'Hunter×hunter = ハンター ハンター',
                'author' => '冨樫, 義博,冨樫義博',
                'publisher' => '集英社',
                'isbn' => '9784088725710',
                'classification' => null,
                'registration_date' => null,
            ],
        ];

        foreach ($books as $book) {
            Book::create($book);
        }
    }
}
